### ISSUE TITLE
Orange ANSI color instead of blue causes confusion

### ISSUE THREAD

**Issue by TokugawaTakesi** [subtheme-pro/monokai-pro#18]
**Describe the bug**

In Editor -> Color Scheme -> Console colors, there is orange color instead of blue:

![image](https://user-images.githubusercontent.com/41653501/116632760-dcd1fa00-a992-11eb-8a85-c25eb0d596b6.png)

Because orange color is being frequently used for warnings while blue is not, it causes the discomfort.

**To Reproduce**

Just check "Editor -> Color Scheme -> Console colors" will be enough.

**Comment by jontaydev** [comment]
So that is by design, if you look at the official editor themes, ansi blue is rendered as orange. I think this is because Monokai Pro uses a limited color palette that doesn't align perfectly with the ansi variables, so the original designer decided to define them like this.

However, I can try to use the colors appropriately when defining tokens. For example, errors should typically be using red, etc. If you see something that doesn't match up with the official VSCode and Sublime themes, let me know. My primary goal right now is to match up the official themes as closely as I can before I make any additional variations.

**Comment by TokugawaTakesi** [comment]
@jontaydev 

Thank you for the quick reaction.

I understand you must obey to color guidelines of Monokai theme.
But must we obey to it even if it will confuse the users?
I suppose it will be like replace the yellow and green colors of traffic lights.

Please consider the adding the harmonious with each Monokai theme blue color for the console as exception.

**Comment by jontaydev** [comment]
There is still more work to be done and I can't start making variations on this theme right now. Maybe when this theme is more complete I can start looking into template parameters that you can configure at build time.

For now, I think it's pretty easy to modify this specific color in JetBrains. Just select the ansi blue value and choose whatever color you think would be appropriate for that variable.

I do understand your concern though - it is a bit annoying. Maybe if you contact the original designer he can provide more insight into this decision.

**Comment by jontaydev** [comment]
This guy found a blue color that works nicely: https://github.com/Monokai/monokai-pro-sublime-text/issues/45#issuecomment-341065531
