### ISSUE TITLE
Unreadable search fields

### ISSUE THREAD

**Issue by derbeneviv** [subtheme-pro/monokai-pro#20]
**Describe the bug**
Ctrl-f found items are unreadable because of too bright yellow, see screenshot  
This is the issue for all four color schemes

Changing white text to black(for example) makes it much more readable

**Screenshots**
current
![изображение](https://user-images.githubusercontent.com/5698025/119844067-c6c34500-bf10-11eb-9b48-3dc836b8c058.png)

black text
![изображение](https://user-images.githubusercontent.com/5698025/119844722-58cb4d80-bf11-11eb-941a-02789274fc56.png)

**Application:**
Intellij Idea Community 2020
Ubuntu 20.04

**Comment by krish-r** [comment]
Hello, 

Thanks for the theme. 

Here's a side-by-side comparison between VS Code and IntelliJ. 
Can you please consider the highlight color from VS Code please, (I believe its #fcfcfa in the default variant).

_Without Ctrl + F:_
![image](https://user-images.githubusercontent.com/54745129/121804179-b5916c80-cc62-11eb-8658-c59cee5177b3.png)

_With Ctrl + F:_
![image](https://user-images.githubusercontent.com/54745129/121804215-e2de1a80-cc62-11eb-88cf-4da65b50e679.png)

**Comment by jontaydev** [comment]
Fixed in version 1.3, will be available when approved: https://plugins.jetbrains.com/plugin/13643-monokai-pro-theme/versions/stable/125907. 

For now colors are matching VSCode theme, however I noticed Sublimes uses different coloring (yellow bg for currently selected result, normal bg with border for other results). I am open to feedback if Sublime colors are preferred.
